# Generated by Django 3.1.2 on 2020-11-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201103_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='value',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
