# Generated by Django 3.1.2 on 2020-11-07 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20201107_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient',
            new_name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='value',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
