# Generated by Django 3.1.2 on 2020-11-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20201107_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
