# Generated by Django 3.1.2 on 2020-11-08 12:35

from django.db import migrations
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=recipes.models.ListField(),
        ),
    ]
